version: '3.8'

services:
  web:
    image: php:8.2-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  db:
    image: mysql:latest
    restart: always
    volumes:
      - db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: docker_php
      MYSQL_USER: protik
      MYSQL_PASSWORD: protik123

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      # - PMA_ARBITRARY=1

volumes:
  db: {}
