# version: '3'

services:
  web:
    image: php:8.2-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
  

  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql/
    
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=docker_php
      - MYSQL_PASSWORD=my_pass
      - MYSQL_USER=root

volumes:
  db:
