FROM php:8.2-apache

RUN docker-php-ext-install mysqli

# Install system dependencies needed for Composer
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    git \
    zip \
    && rm -rf /var/lib/apt/lists/*


# Install Node.js (LTS 18)
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

# Verify Node.js & npm installation (optional)
RUN node -v && npm -v

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Enable Apache rewrite module (useful for Laravel, etc.)
RUN a2enmod rewrite

# Set working directory
WORKDIR /var/www/html
